apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: uat-
configMapGenerator:
  - name: springboot-template
    files:
      - application_config_override.yaml
    literals:
      - MAX_JVM_MEMORY=512
      - MIN_JVM_MEMORY=512
secretGenerator:
  - name: springboot-template
    files:
      - application_secret_override.yaml
images:
  - name: ghcr.io/zawthanoo/springboot-template
    newName: ghcr.io/zawthanoo/springboot-template
    newTag: ghcr.io/zawthanoo/springboot-template:1.0.0-25-c6474f6
