apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: uat-
configMapGenerator:
  - name: spring-rest-helloworld
    files:
      - application_config_override.yaml
    literals:
      - MAX_JVM_MEMORY=512
      - MIN_JVM_MEMORY=512
secretGenerator:
  - name: spring-rest-helloworld
    files:
      - application_secret_override.yaml
images:
  - name: ghcr.io/zawthanoo/spring-rest-helloworld
    newName: ghcr.io/zawthanoo/spring-rest-helloworld
    newTag: 1.0.0-3-869c624
