apiVersion: v1
kind: Service
metadata:
  name: spring-rest-helloworld
  labels:
    app: spring-rest-helloworld  
spec:
  selector:
    app: spring-rest-helloworld
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
