apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: uat-

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/zawthanoo/angular-mfe-module-1
    newName: ghcr.io/zawthanoo/angular-mfe-module-1
    newTag: 2-9517054
