apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: angular-mfe-shell
  files:
    - application_config_override.yaml
  literals:
    - MAX_JVM_MEMORY=256
    - MIN_JVM_MEMORY=256  
      
secretGenerator:
- name: angular-mfe-shell
  files:
    - application_secret_override.yaml

images:
- name: ghcr.io/zawthanoo/angular-mfe-shell
  newName: ghcr.io/zawthanoo/angular-mfe-shell
  newTag: 1.0.0-5-1d957df