apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: angular-mfe-shell
    files:
      - mf.manifest.json
      
images:
  - name: ghcr.io/zawthanoo/angular-mfe-shell
    newName: ghcr.io/zawthanoo/angular-mfe-shell
    newTag: 12-5e911ae