apiVersion: v1
kind: Service
metadata:
  name: springboot-template
  labels:
    app: springboot-template  
spec:
  selector:
    app: springboot-template
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: 8282-tcp
      port: 8282
      protocol: TCP
      targetPort: 8282
