apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-mfe-shell
  labels:
#    pipelinesascode.tekton.dev/on-event: pull_request
#    pipelinesascode.tekton.dev/on-target-branch: devteam
#    repo_name: angular-mfe-shell
    app: angular-mfe-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-mfe-shell
  template:
    metadata:
      labels:
        app: angular-mfe-shell
    spec:
      containers:
        - name: angular-mfe-shell
          image: ghcr.io/zawthanoo/angular-mfe-shell:1.0.0-5-70eccea
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: angular-mfe-shell
          resources:
            requests:
              memory: 512Mi
          volumeMounts:
            - name: angular-mfe-shell-config-volume
              readOnly: true
              mountPath: "/usr/share/nginx/html/angular-mfe-shell/assets/mf.manifest.json"
              subPath: mf.manifest.json
      imagePullSecrets:
        - name: ghcr-io-registry
      volumes:
        - name: angular-mfe-shell-config-volume
          configMap:
            name: angular-mfe-shell
            items:
              - key: mf.manifest.json
                path: mf.manifest.json
