apiVersion: v1
kind: Service
metadata:
  name: angular-mfe-shell
  labels:
    app: angular-mfe-shell  
spec:
  selector:
    app: angular-mfe-shell
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: 8282-tcp
      port: 8282
      protocol: TCP
      targetPort: 8282
